### ISSUE TITLE
Replace SLOT mechanism with annotations

### ISSUE THREAD

**Issue by PhilBeaudoin** [ArcBees/GWTP#236]
The current slot mechanism has always annoyed me because it requires defining a bunch of constants and writing a smelly catch-all if/else method. An alternate and much less verbose option could be to use annotations in the view to indicate widgets corresponding to slots.

For example:
@SlotContainer(Top.class) @UiField FlowPanel topPanel;

For more complex cases, where you need some logic we could support slot-related methods in the presenter, for example:

@SetInSlot(Top.class)
public void setInTopSlot(Widget content) { ... }

@AddToSlot(Top.class)
public void addToTopSlot(Widget content) { ... }

In all these examples Top is a public static nested class of the presenter inheriting from some base Slot class. There is no need for the @ContentSlot annotation. The generator could ensure that every slot a matching @SlotContainer or slot methods.

It should be possible to support these at the same time as the old mechanism, although we could even considering deprecating the old system as I believe anything that could be done before can be done with this approach -- usually in a much less verbose way.

**Comment by meriouma** [comment]
@rdwallis Does your implementation take care of this issue?

**Comment by rdwallis** [comment]
Yes use the bindSlot method in your view's constructor in 1.5-SNAPSHOP
