### ISSUE TITLE
Dispatch Spring Server Issue with ActionImpl

### ISSUE THREAD

**Issue by BenDol** [ArcBees/GWTP#289]
~~I have integrated Spring as my server DI and have ran into 2 issues actually:~~

Read comments below to track how this has progressed so far.

**Running:** GWTP ~~0.7~~ 1.0

~~1) Dispatch Spring Server is throwing: `"org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'dispatch' is defined"`. Which means its not picking up on DispatchServiceImpl `@Component` ([more information](http://stackoverflow.com/questions/17607570/gwtp-dispatch-spring-issue-no-bean-named-dispatch-is-defined)). I was able to hack this by creating a copy of DispatchServiceImpl in my project where Springs component scanning is finding this component. (This is happening in my GWTP 1.0 also using the spring sample provided. I'm not running maven here, but I struggle to see how that would affect it - if this is effecting it then perhaps I can find out how to resolve it).~~

~~2) With my what I'm assuming to be a hack fix to this issue in place (I could be wrong) the bean is now being found and the ActionImpl falls over with this error:~~

~~If I change them to UnsecuredActionImpl it works fine. I have seen that 0.7 has a bug with the security cookie being NULL, but I applied this fix in the google code repository and it did not resolve this issue. If someone could atleast shed some light on this, I would be very grateful :) Thanks for taking the time to read!~~

**My Setup Files (Updated)**

ServerModule.java:
```java
/**
 * Module which binds the handlers and configurations.
 */
@Configuration
@Import({DefaultModule.class, PropertyModule.class})
@ImportResource("classpath:META-INF/properties.xml")
@ComponentScan({"com.test", "com.gwtplatform.dispatch.server.spring"})
public class ServerModule extends HandlerModule {
	
    public ServerModule() {
    }

    @Bean
    public ActionValidator getDefaultActionValidator() {
        return new DefaultActionValidator();
    }

    @Bean
    public LoggerFactoryBean getLogger() {
        Logger logger = Logger.getAnonymousLogger();
        logger.setLevel(Level.FINEST);
        return new LoggerFactoryBean(logger);
    }

    protected void configureHandlers() {
    	bindHandler(InitDispatchAction.class, InitDispatchHandler.class);
        bindHandler(SendTextToServerAction.class, SendTextToServerHandler.class);
    }
}
```

PropertyModule.java:
```java
@Configuration
public class PropertyModule {

    public PropertyModule() {
    }

    @Bean
    public PropertyOverrideConfigurer getPropertyOverrideConfigurer() {
        PropertyOverrideConfigurer propertyOverrider = new PropertyOverrideConfigurer();

        propertyOverrider.setLocation(new ClassPathResource("META-INF/override.properties"));
        propertyOverrider.setIgnoreResourceNotFound(false);
        propertyOverrider.setIgnoreInvalidKeys(false);
        propertyOverrider.setOrder(0);

        return propertyOverrider;
    }
}
```

web.xml:
```xml
  <!-- Java-based annotation-driven Spring container definition -->
  <context-param>
    <param-name>contextClass</param-name>
    <param-value>org.springframework.web.context.support.AnnotationConfigWebApplicationContext</param-value>
  </context-param>
  
  <context-param>
    <param-name>contextConfigLocation</param-name>
    <param-value>
    	com.test.server.spring
    </param-value>
  </context-param>
  
  <!-- Creates the Spring Container shared by all Servlets and Filters -->
  <listener>
    <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
  </listener>
  
  <listener>
    <listener-class>org.springframework.web.context.request.RequestContextListener</listener-class>
  </listener>
  
  <servlet>
    <servlet-name>dispatch</servlet-name>
    <servlet-class>org.springframework.web.context.support.HttpRequestHandlerServlet</servlet-class>
  </servlet>
  
  <servlet-mapping>
    <servlet-name>dispatch</servlet-name>
    <url-pattern>/dispatch/*</url-pattern>
  </servlet-mapping>
  
  <!-- Default page to serve -->
  <welcome-file-list>
    <welcome-file>Gwtpsamplespring.html</welcome-file>
  </welcome-file-list>
```

Regards,
Ben

**Comment by alekseipot** [comment]
Hello, I cloned repo https://github.com/ArcBees/GWTP-Samples/tree/master/gwtp-samples/gwtp-sample-basic-spring

Run module from master using maven gwt pluggin, and got:
<code>
An error occured: Cookie provided by RPC doesn't match request cookie, aborting action, possible XSRF attack. (Maybe you forgot to set the security cookie?) While executing action: com.gwtplatform.samples.basicspring.shared.dispatch.SendTextToServerAction
</code>

Same problem on demo platform:
http://gwtp-sample-basic-spring.appspot.com/#response;textToServer=sadad

Could you please explain, what am I  doing wrong?

**Comment by olafleur** [comment]
Do you still have this problem with GWTP 1.5.1 ?

**Comment by alekseipot** [comment]
HI,
All is ok now
Thnaks for replay:)

2016-01-04 21:50 GMT+03:00 Olivier Lafleur <notifications@github.com>:

**Comment by AdamSantosCA** [comment]
I have just come across this issue in our production environment. We are using GWTP 1.5.3 running in Google App Engine. I found that the solution @ilucker and @BenDol were discussing to patch DispatchServiceImpl would not work properly due to App Engine using an old version of javax.servlet.GenericServlet that is included in Tomcat as seen here: http://www.docjar.com/html/api/javax/servlet/GenericServlet.java.html

In this version, the getServletName() method just returns "config.getServletName();". Since the fix proposed by @ilucker does not set the private config in GenericServlet, it will still throw a NullPointerException. @BenDol's additional change to override getServletName() helps, but it still creates a situation where DispatchServiceImpl and its parent can have two different ServletConfigs.

Has anyone found a reliable way to ensure that the config is properly set in GenericServlet without modifying DispatchServiceImpl?

Thanks,
Adam
