### ISSUE TITLE
CodeSplitting with PresenterWidget

### ISSUE THREAD

**Issue by confile** [ArcBees/GWTP#333]
Usually you do CodeSplitting with Proxy annotation of you Presenters Proxy.

Assume you have a GWTP app embedded in a website. Like a wether widget or some much more complex app. Then you do not need to have a history support. Or in other words you cannot control the history.

How would you suggest to do code splitting in this case?

**Comment by sameepsinghania** [comment]
is this thread closed?
If yes what the valid way to put presenterwidget behind a split point?
