### ISSUE TITLE
Support global Http configuration through Dispatcher

### ISSUE THREAD

**Issue by reinert** [ArcBees/GWTP#418]
It would be (very) useful if we could configure the Dispatcher to execute some actions to Requests/Responses under certain circumstances. Indeed, it further justifies the use of a central component to handle all commands.

So, as we are in the HTTP context, I think we should have an option to set:
* Http param - what kind of param you want to append to requests? Header, query, form(? - not allowed in every method).
* Key - what will be the name of the param?
* Value - what will be the value of the param? Some callback receiving the Request and returning String would be nice
* Http method - to which method(s) would you like to apply this param? You could then determine that you want this specific param to be added only when Post requests are made; or you could set to all methods.

HttpParam + Key + Value would be the *action* itself (maybe Enhancer or RequestEnhancer) to apply upon the requests.
The HttpMethod is part of the *configuration* telling when to apply the action. (I can't think of a name to it for now)

We then bind some *action (enhancer)* along with some *configuration (telling when to apply the enhancer)* to the Dispatcher in order to active this desired behavior.

Ideas are welcome!

**Comment by olafleur** [comment]
Closing, then. Feel free to reopen it if you think it should be readressed.
