### ISSUE TITLE
Update Road Map

### ISSUE THREAD

**Issue by spg** [ArcBees/GWTP#426]
As reported by @twistedpair (https://groups.google.com/forum/#!topic/gwt-platform/qYzIPHQQLII) , we should update the Road Map page to better reflect the current state of GWTP.

**Comment by olafleur** [comment]
Closing, as we don't have a public roadmap page anymore.
See that video : https://www.youtube.com/watch?v=ShsN_M1L1C8
if you’re curious about where we are going with the next major version of GWTP.
He gives a glimpse at the end of the talk about what lies ahead for GWTP.
