### ISSUE TITLE
How can I determine if the user clicked the back button?

### ISSUE THREAD

**Issue by confile** [ArcBees/GWTP#491]
I use GWTP and have two Presenters. Lets call it

FirstPresenter
SecondPresenter
The website starts with First. When I click a link on First I navigate to Second. Now there are two forms of navigation on the Second Presenter.

1. The user can click a link which navigates back to First
2. The user can click the browser back button.

How can I determine if the browser back button has been clicked?

**Comment by olafleur** [comment]
Closing, as this issue is more than a year old. Feel free to reopen if you still have the issue with the current version.
