### ISSUE TITLE
Atmosphere Jersey with GWTP REST

### ISSUE THREAD

**Issue by confile** [ArcBees/GWTP#503]
In GWT Rest you would do something like this: 

```
dispatcher.execute(carId, carService.save(car), new RestCallback<Car>() {
    @Override
    public void setResponse(Response response) {
        logger.debug("Response received > "+ response.getStatusCode() + ": "+ response.getStatusText());
    }

    @Override
    public void onSuccess(Car car) {
        onCarSaved(car);
    }
});
```

When using the Atmosphere Framework (https://github.com/Atmosphere/atmosphere) I could use Jersey for the communication. 

Using atmosphere on the server the server could push to the client when updates are available. This means that the public void onSuccess(Car car) would be called more than once.

Is it possible to integrate the Atmosphere Push into the GWTP REST service somehow?

**Comment by olafleur** [comment]
Should we close that issue or is it something that we want to implement?

**Comment by christiangoudreau** [comment]
Well, it's a little bit outdated, but there's an Impl for gwt for Atmosphere

https://github.com/Atmosphere/atmosphere-extensions/wiki/Atmosphere-GWT-2.0
