### ISSUE TITLE
Broken client action caching

### ISSUE THREAD

**Issue by kuhnroyal** [ArcBees/GWTP#513]
I have updated to the latest version a while back but yesterday I decided to move from .dispatch to .dispatch.rpc and nothing is working as expected.

The result callback that is constructed in [AbstractCachingClientActionHandler:91](https://github.com/ArcBees/GWTP/blob/master/gwtp-core/gwtp-dispatch-common-client/src/main/java/com/gwtplatform/dispatch/client/actionhandler/caching/AbstractCachingClientActionHandler.java#L90) which handles the postfetch is completely disregarded in [DelegatingAsyncCallback:68](https://github.com/ArcBees/GWTP/blob/1f077818353d9b2ae9c48481da5dadba7f5a862d/gwtp-core/gwtp-dispatch-common-client/src/main/java/com/gwtplatform/dispatch/client/DelegatingAsyncCallback.java#L68). Client caching is completely broken as far as I can tell.

**Comment by olafleur** [comment]
Closing, as this issue is more than a year old. Feel free to reopen if you still have the issue with the current version.
