### ISSUE TITLE
In the carstore, put DebugIds in a constant class

### ISSUE THREAD

**Issue by jclariviere** [ArcBees/GWTP#520]
As suggested by @meriouma in https://github.com/ArcBees/GWTP/pull/519#discussion_r14611610

**Comment by olafleur** [comment]
@jclariviere Do you still want to do that change?
If not, maybe you should close that issue.

**Comment by jclariviere** [comment]
I had forgotten about that one! But when time permits, it would be a good idea to do the change since this is an example to show best practices.

**Comment by meriouma** [comment]
Moved to https://github.com/ArcBees/GWTP-Samples
Implemented in https://github.com/ArcBees/GWTP-Samples/pull/73
