### ISSUE TITLE
Feature request: RestDispatchAsync running on a Web Worker Thread

### ISSUE THREAD

**Issue by confile** [ArcBees/GWTP#548]
I think it would be a great improvement to run the RestDispatchAsync on a Web Worker Thread and post back the result of the request to the main thread when the data has been arrived.

**Comment by meriouma** [comment]
I agree with Richard, I don't really see the benefits at this point since the ajax call is by nature async.
I think this is an interesting post (and benchmark!) : http://stackoverflow.com/questions/18768452/web-workers-handling-ajax-calls-optimisation-overkill
