### ISSUE TITLE
Presenter Slots Wiki Page could be clearer

### ISSUE THREAD

**Issue by rdwallis** [ArcBees/GWTP#621]
https://github.com/ArcBees/GWTP/wiki/Presenter-%22Slots%22 is not very clear.  A lot of knowledge is assumed and I'm not sure if Layout Presenters and Nested Presenters are two names for the same thing or two different things.

I don't think a person who didn't know how slots work would be able to come to a full understanding from that page.

**Comment by olafleur** [comment]
@tusharbhasme Would you like to submit a pull request with these modifications in the doc? I think it would help. Thanks for your ideas on the clarification of the doc, it is really appreciated.

**Comment by christiangoudreau** [comment]
http://dev.arcbees.com/gwtp/ to submit your change (see github logo at the top of the page you wish to submit changes)

**Comment by tusharbhasme** [comment]
Sure!

**Comment by rdwallis** [comment]
Thanks for the contribution!!
