### ISSUE TITLE
GWT 2.7 GWTP 1.4-SNAPSHOT  Cannot find GinjectorExtension

### ISSUE THREAD

**Issue by fpizzichillo** [ArcBees/GWTP#650]
Hi folks.
I have a problem when I want to run the superDevMode (mvn gwt:run) . The following error appears as if he could not find the GinjectorExtension 
 Rebinding com.gwtplatform.mvp.client.ApplicationController
[INFO]                Invoking generator com.gwtplatform.mvp.rebind.ApplicationControllerGenerator
[INFO]                   [ERROR] Cannot find ar.org.amr.autorizadorWeb.client.gin.GinjectorExtension
[INFO] com.google.gwt.core.ext.typeinfo.NotFoundException: ar.org.amr.autorizadorWeb.client.gin.GinjectorExtension
[INFO] 	at com.google.gwt.dev.javac.typemodel.TypeOracle.getType(TypeOracle.java:623)
[INFO] 	at com.google.gwt.dev.javac.typemodel.TypeOracle.getType(TypeOracle.java:68)
[INFO] 	at com.gwtplatform.mvp.rebind.AbstractGenerator.getType(AbstractGenerator.java:110)
[INFO] 	at com.gwtplatform.mvp.rebind.GinjectorGenerator.addExtensionInterfaces(GinjectorGenerator.java:165)
[INFO] 	at com.gwtplatform.mvp.rebind.GinjectorGenerator.initComposer(GinjectorGenerator.java:155)
[INFO] 	at com.gwtplatform.mvp.rebind.GinjectorGenerator.generate(GinjectorGenerator.java:88)
[INFO] 	at com.gwtplatform.mvp.rebind.ApplicationControllerGenerator.generate(ApplicationControllerGenerator.java:84)

The module.gwt.xml has the following line 
<set-configuration-property name="gin.ginjector.extensions"
		value="ar.org.amr.autorizadorWeb.client.gin.GinjectorExtension" />

The ar.org.amr.autorizadorWeb.client.gin.GinjectorExtension interface exists and is in the classPath

Any advice?
Regards 
Fabricio

**Comment by fpizzichillo** [comment]
Hi Folks.
Sorry for the delay, I was on vacation.
@Chris-V  used extend-configuration-property but with the same results (gwtp 1.4).

**Comment by fpizzichillo** [comment]
Could anything in common with https://github.com/ArcBees/GWTP/issues/614 ??

Regards

**Comment by meriouma** [comment]
Do you still have this issue with GWTP-1.4?

**Comment by meriouma** [comment]
Could you confirm this is still an issue?

**Comment by fpizzichillo** [comment]
Hi Folks.
Sorry for the delay. I can confirm that the bug has been resolved @meriouma @Chris-V 
Thanks!
