### ISSUE TITLE
Version check warns of new version, even when on latest

### ISSUE THREAD

**Issue by shawnjohnson** [ArcBees/GWTP#658]
I recently updated to 1.3.1, when I run gwt-compile I get warnings that there is a newer version available, yet at this time, 1.3.1 is the latest available.

```
Compiling module...
...
...
   Invoking Linker Verify the availability of a more recent version of GWTP.
      Checking version information for gwtp-mvp-client
         [WARN] ------------------------------------------------------------
         [WARN] A new version of gwtp-mvp-client is available!
         [WARN] Your version: 1.3.1
         [WARN] Latest version: 
         [WARN] See http://search.maven.org/#artifactdetails|com.gwtplatform|gwtp-mvp-client||jar
         [WARN] ------------------------------------------------------------
      Checking version information for gwtp-dispatch-rpc-client
         [WARN] ------------------------------------------------------------
         [WARN] A new version of gwtp-dispatch-rpc-client is available!
         [WARN] Your version: 1.3.1
         [WARN] Latest version: 
         [WARN] See http://search.maven.org/#artifactdetails|com.gwtplatform|gwtp-dispatch-rpc-client||jar
         [WARN] ------------------------------------------------------------
   Link succeeded
   Compilation succeeded -- 107.134s
```

**Comment by rdwallis** [comment]
Just ran a compile on a 1.3.1 project and it detects that it's the latest version correctly.

How long has this been happening?  Is it only for one project or multiple projects?

**Comment by shawnjohnson** [comment]
Just the one project, and I just upgraded this week. May be isolated, but
wanted to share my experience.

**Comment by rdwallis** [comment]
Yes thanks for reporting.

Does it happen everytime? Even after cleaning the project directory?

**Comment by rdwallis** [comment]
I'm encountering this bug as well now running a 1.3.1 project.

**Comment by christiangoudreau** [comment]
1.4 is out, right? :D

**Comment by rdwallis** [comment]
That explains it.  Makes this much easier to reproduce :)

Our releases need more fanfare.

**Comment by christiangoudreau** [comment]
A message is being written, but we wanted to keep it for the GWT.Create :D

**Comment by valsoray17** [comment]
I'm seeing it for 1.4. And the number for "Latest version:" is empty

**Comment by Chris-V** [comment]
Are you using gwtp-all by all means?

**Comment by valsoray17** [comment]
Nope, I'm using selective modules

**Comment by valsoray17** [comment]
After cleaning and building all modules the warning went away. Sorry for the confusoin

**Comment by Chris-V** [comment]
Thanks. I'm gonna close for now as none of us can reproduce. If anyone happen to reproduce it, feel free to reopen this issue.

**Comment by haridaniel** [comment]
How can I just avoid this warning? Thanks
