### ISSUE TITLE
Latest 1.4-SNAPSHOT (43) breaks build

### ISSUE THREAD

**Issue by gsine** [ArcBees/GWTP#659]
Hi,
Maven downloaded the latest snapshots today, and it seems like something is broken.
I am getting the following errors, which I did not get in snapshots downloaded until Dec 12.

[INFO]       Tracing compile failure path for type 'org.vsabha.VSabha.UIEngine.VSW.shared.api.RSIDepartmentImpl'
[INFO]          [ERROR] Errors in '/home/gpn/workspace/vsabha/UIEngine/VSWebServe/target/.generated/org/vsabha/VSabha/UIEngine/VSW/shared/api/RSIDepartmentImpl.java'
[INFO]             [ERROR] Line 33: The constructor RSIDepartmentImpl_0_create(String, String, RSMDepartment) is undefined
[INFO]       See snapshot: /tmp/org.vsabha.VSabha.UIEngine.VSW.shared.api.RSIDepartmentImpl6498410689067693963.java

This error occurs for every Rest Service Implementation that I have.

I am heavily tied to the new ResourceDelegate infra-structure, and hence rolling back to something is very difficult.
GWT version: 2.6.0.
GWTP version: 1.4-SNAPSHOT.

Any help is greatly appreciated.

Thanks and Best Regards,
GPN

Here are the GWT and GWTP dependencies I have in my pom.xml.
    
    <dependency>
      <groupId>com.google.gwt</groupId>
      <artifactId>gwt-user</artifactId>
      <version>${gwt.version}</version>
    </dependency>
    <dependency>
      <groupId>com.google.gwt</groupId>
      <artifactId>gwt-servlet</artifactId>
      <version>${gwt.version}</version>
    </dependency>
    <dependency>
      <groupId>com.google.gwt</groupId>
      <artifactId>gwt-dev</artifactId>
      <version>${gwt.version}</version>
      <scope>provided</scope>
    </dependency>

    
    <dependency>
      <groupId>com.gwtplatform</groupId>
      <artifactId>gwtp-mvp-client</artifactId>
      <version>${gwtp.version}</version>
    </dependency>
    <dependency>
      <groupId>com.gwtplatform</groupId>
      <artifactId>gwtp-dispatch-rpc-client</artifactId>
      <version>${gwtp.version}</version>
    </dependency>
    <dependency>
      <groupId>com.gwtplatform</groupId>
      <artifactId>gwtp-dispatch-rpc-server-guice</artifactId>
      <version>${gwtp.version}</version>
    </dependency>
    <dependency>
      <groupId>com.gwtplatform</groupId>
      <artifactId>gwtp-dispatch-rest</artifactId>
      <version>${gwtp.version}</version>
    </dependency>
    <dependency>
      <groupId>com.gwtplatform</groupId>
      <artifactId>gwtp-dispatch-rest-shared</artifactId>
      <version>${gwtp.version}</version>
    </dependency>
    <dependency>
      <groupId>com.gwtplatform.extensions</groupId>
      <artifactId>dispatch-rest-delegates</artifactId>
      <version>${gwtp.version}</version>
    </dependency>

**Comment by Chris-V** [comment]
Thanks for reporting. It appears our CI didn't deploy the snapshot
automatically with the last merge. It should be available now.

**Comment by rdwallis** [comment]
Sorry for the cleaning misdirection.  Thanks for reporting.

**Comment by gsine** [comment]
Works now. Thanks Richard, Chris, for the help.
