### ISSUE TITLE
RestDispatch - RestAction problem

### ISSUE THREAD

**Issue by baczek00** [ArcBees/GWTP#665]
Hello,

How to use GWTP-Rest without all GWTP?

Guice and Gin I configured but can not keep to write RestAction

How to write RestAction?

My code:
```
public class RestGWTPTutorial implements EntryPoint {
 
  /**
   * This is the entry point method.
   */
  public void onModuleLoad() {
	  InjectorDispatch dispatch = GWT.create(InjectorDispatch.class);
	  dispatch.getRestDispatch().execute(action, callback)
      
    }
```

**Comment by meriouma** [comment]
Can you add the source code of InjectorDispatch?

**Comment by baczek00** [comment]
```
@GinModules(value = {DispatchModule.class})
public interface InjectorDispatch extends Ginjector {

	public RestDispatch getRestDispatch();
}
```

**Comment by meriouma** [comment]
Try changing `@GinModules(value = {DispatchModule.class})` to `@GinModules(value = {DispatchModule.class}, properties = {"gin.ginjector.modules"})`

**Comment by baczek00** [comment]
your textbook example:
```
dispatcher.execute(carsResource.car(mycarId).delete()
        new AsyncCallback<Car>() {
            @Override
            public void onSuccess(Void nothing) { /* snip */ }

            @Override
            public void onFailure(Throwable caught) { /* snip */ }
        });
```
How to achieve this
```
carsResource.car(mycarId).delete()
```

**Comment by meriouma** [comment]
This comes from the carstore sample : https://github.com/ArcBees/GWTP-Samples/tree/master/carstore

Basically, you need to define REST service interfaces to be able to use them.

```java
@Path("/cars")
@Produces(MediaType.APPLICATION_JSON)
public interface CarsResource {
    @Path("{id"})
    CarResource car(@PathParam("id") Long carId);
}
```

```java
@Produces(MediaType.APPLICATION_JSON)
public interface CarResource {
    @DELETE
    RestAction<Void> delete();
}
```

You also need to add a method in your Ginjector : `CarsResource getCarsResource();`

**Comment by baczek00** [comment]
Hello,
Thank you for trying to help.

But can not keep to understand the principles of operation without GWTP. Could you prepare for an example of using?

Regards,

**Comment by olafleur** [comment]
Hi @baczek00 : what did you manage to do until now? What part are you missing?

**Comment by olafleur** [comment]
This issue has been open for more than 6 months. Closing. Please reopen as needed.
