### ISSUE TITLE
Extend PresenterWidget.fireEvent() to support generic Event

### ISSUE THREAD

**Issue by timeu** [ArcBees/GWTP#668]
Currently the `fireEvent()` function support only `GwtEvent<?>` as paramter. 
`GwtEvent` extends from `Event`. 

According to http://www.gwtproject.org/javadoc/latest/com/google/gwt/event/shared/GwtEvent.html one should use `Event` instead of `GwtEvent`: 

<pre>
There is no need for an application's custom event types to extend GwtEvent. Prefer Event instead.
</pre>

It would be handy if the `fireEvent` function would be extended to support the more generic `Event` type. 

The current workaround is: `getEventBus().fireEventFromSource(new MyEvent(),this);`

**Comment by rdwallis** [comment]
@timeu  thanks for reporting.  Can you implement and do a PR for this?

**Comment by timeu** [comment]
Sure, 
I forked it and tried to run mvn clean test but apparently it can't find the arcbees-checkstyle configuraiton: 
`Failure to find com.arcbees:checkstyle:jar:1.0-SNAPSHOT`

Any pointers how to fix it ?
