### ISSUE TITLE
Testing removeFromSlot(Object slot, IsWidget content)

### ISSUE THREAD

**Issue by slugmandrew** [ArcBees/GWTP#683]
After upgrading from 1.3.1 to 1.4, my Jukito tests now fail at any line that verifies removing a PresenterWidget from a slot, such as:

`verify(myView).removeFromSlot(ViewAccountPresenter.SLOT_comments, commentsPresenter);`

Rolling back to 1.3.1 fixes this issue and tests pass again.

Strangely, testing for setInSlot() still works fine.

**Comment by rdwallis** [comment]
Hi Drew

Presenter behavior has changed in 1.4.

In 1.3.1 if you call removeFromSlot then it will always call onHide even if
it the presenter is already hidden.

In 1.4 the onHide methods will not be called if the presenter is already
hidden.

Also nothing will happen if you're removing the presenter from a slot that
it isn't in. (I think this might have been the same in 1.3.1 but mentioning
it just in case.).

So ensuring that the presenter is visible before testing if it hides
correctly should fix your tests.

If that doesn't work maybe sharing the failing test will help us track down
the problem.

**Comment by slugmandrew** [comment]
Hey Richard,

Thanks for the reply. I was in fact calling removeFromSlot() for all child presenters in my parent presenter's onHide() method - so as to remove them whether they were added or not. It was a pretty redundant test anyway (I was just getting used to Jukito/Mockito).

Thanks for the clarification!

Drew
