### ISSUE TITLE
Lack of documentation on deprecation of addHandler

### ISSUE THREAD

**Issue by christiangoudreau** [ArcBees/GWTP#686]
Coming from the forum: 
With 1.4 the method PresenterWidget#addHandler is depcrecated without any hint what method we have to use instead. Should we use PresenterWidget#addRegisteredHandler from now on?

**Comment by olafleur** [comment]
From the release notes : "Client Action Handlers: You are recommended to use the more flexible Interceptors." Maybe we should have something more clear somewhere? Maybe in the Migration notes? @Chris-V ?
