### ISSUE TITLE
No documentation available for GWTP

### ISSUE THREAD

**Issue by jwendel** [ArcBees/GWTP#688]
https://github.com/ArcBees/GWTP/wiki just has a link to http://dev.arcbees.com/gwtp/.  Then the link on that page to "GWTP Documentation" just links back to https://github.com/arcbees/gwtp/wiki

**Comment by Chris-V** [comment]
This is odd. All the documentation displays fine for me. Could you post a screenshot please? Is there any errors in the javascript debugging tool?

**Comment by meriouma** [comment]
There's a link : `GWTP Documentation - Find out how to use GWT-Platform here.` that points to https://github.com/arcbees/gwtp/wiki

**Comment by BenDol** [comment]
![issue](https://cloud.githubusercontent.com/assets/1935706/6628359/a1ad097a-c969-11e4-94f4-2fb59bc20481.png)

**Comment by Chris-V** [comment]
Ha, nice catch. This link should be changed to something like "GitHub repository". There's a menu on the left though to navigate the documentation.

**Comment by olafleur** [comment]
Closing as, from what I can see, the link is not on that page anymore.
