### ISSUE TITLE
How to use CachingInterceptor

### ISSUE THREAD

**Issue by Isakaras** [ArcBees/GWTP#698]
Hello,

I'm trying to use your new Interceptors, but can't get CachingInterceptor to work.
I would like to use an Interceptor which extends from CachingInterceptor, so that basic caching functionality is built in?!

If I use @Inject like this:
```java
	@Inject
	public GetGwtUserInterceptor(Class<GetGwtUserAction> actionType, Cache cache) {
		super(actionType, cache);
	}
```
I get an error:
[ERROR] Error injecting java.lang.Class<com.denkbares.ssp.shared.dispatch.GetGwtUserAction>: Unable to create or inherit binding: No @Inject or default constructor found for java.lang.Class<com.denkbares.ssp.shared.dispatch.GetGwtUserAction>

But this class does have a default constructor.

If I don't use @Inject, I have no idea how to call the super constructor correctly.
Using AbstractRpcInterceptor instead works, but that's easy because the constructor call only expects one argument which is the class of the action.

Could you please provide me with a basic example how to use CachingInterceptor?

Thank you.

**Comment by BenDol** [comment]
I don't think you need the `Class<GetGwtUserAction> actionType` argument, perhaps just do this:
```
    @Inject
    public GetGwtUserInterceptor(Cache cache) {
        super(GetGwtUserAction.class, cache);
    }
```
Not sure if that will resolve the issue for you, but that seems correct, since GIN doesn't know how to inject that Class object.

**Comment by olafleur** [comment]
@Isakaras Did you manage to do what you wanted? Do you need further help?

**Comment by olafleur** [comment]
Closing as, from what I can see, the question has been answered.
