### ISSUE TITLE
Presenter vs. PresenterWidget

### ISSUE THREAD

**Issue by steffimueller** [ArcBees/GWTP#700]
Is there a logical difference between a Presenter which has no place, i.e., has only a Proxy instead of a ProxyPlace and a PresenterWidget?

**Comment by Elrhino** [comment]
A Presenter which has a Proxy can be used as a Parent Presenter for other Presenters using a [Slot](http://dev.arcbees.com/gwtp/core/slots/) (think about a Root Presenter for your application). 

[PresenterWidgets](http://dev.arcbees.com/gwtp/core/presenters/index.html) allow you to reuse UI components across your application (think about a form or a template).

**Comment by olafleur** [comment]
@steffimueller Hope that answers your question. If you have followup questions, don't hesitate to ask them on the Google Groups : https://groups.google.com/forum/#!forum/gwt-platform
