### ISSUE TITLE
Rest Dispatch Sending Incorrect Path

### ISSUE THREAD

**Issue by BenDol** [ArcBees/GWTP#701]
I have a Rest "resource" set up like so:
```java
/**
 * The protocol for rest controller: {@link nz.co.doltech.actions.server.controllers.ManagementsController}
 */
@Path(Managements.ROOT) // /managements
public interface ManagementsProtocol extends Protocol {

	@POST
	@Path(PATH_REQUEST_COUNT) // /request_count
	RestAction<RequestCounts> getRequestCounts(Filter filter);
}
```

When I call `getRequestCounts` it sends the following HTTP path to the server: `/actions/api/managements/managements/request_counts` doubling up the 'managements' path.

This of course results in: 
```
[org.springframework.web.servlet.PageNotFound] - No mapping found for HTTP request with URI [/actions/api/managements/managements/request_counts] in DispatcherServlet with name 'mvcServlet'
```

Since the Controller is setup for `*/managements/request_count`.

**Comment by BenDol** [comment]
Here are the generated files: 
* [ManagementsProtocolImpl_0_getRequestCounts.java](https://gist.github.com/BenDol/19d2b04a60c34847acc0)
* [ManagementsProtocolImpl.java](https://gist.github.com/BenDol/092aaca87a147b373aec)

**Comment by Chris-V** [comment]
What version? Can you copy the definition of both `Managements.ROOT` and `PATH_REQUEST_COUNT`? Thanks

**Comment by BenDol** [comment]
Version: 1.4
```java
	/*
	  Management API Branch
	 */

	/** Managements API Structure, root: {@value Managements#ROOT} */
	public static interface Managements extends PathBranch {
		public static final String ROOT = "/" + Params.MANAGEMENTS;
		public static final String PATH_ID = "/{" + Params.ID + "}";
		public static final String PATH_REQUEST_COUNT = "/request_counts";

		/** Resource specific params */
		public static interface Params {
			public static final String MANAGEMENTS = "managements";
			public static final String ID = MANAGEMENTS + "_" + RestParams.ID;
		}
	}
```

**Comment by Chris-V** [comment]
I don't understand why you get `/managements` twice. We use 1.4 in many projects and the paths are all good. What is bound to your `@RestApplicationPath` constant?

**Comment by BenDol** [comment]
I've used it fine in the past too without this issue. Seems like some rare bug to me.

**Comment by BenDol** [comment]
```java
        @RestApplicationPath
	@Provides String getApplicationPath() {
		String baseUrl = GWT.getHostPageBaseURL();
		if (baseUrl.endsWith("/")) {
			baseUrl = baseUrl.substring(0, baseUrl.length() - 1);
		}
		return baseUrl + Rest.ROOT;
	}
```

**Comment by meriouma** [comment]
I think we might have to rework the `@RestApplicationPath`. I already experienced the issue and what I ended up doing is `bindConstant().annotatedWith(RestApplicationPath.class).to(EndPoints.ROOT);`, and not include the EndPoints.ROOT in the services path.

**Comment by BenDol** [comment]
So remove the `+ Rest.ROOT` from my getApplicationPath provider? and add that constant bind as you mentioned?

**Comment by meriouma** [comment]
Can you try removing your Provider method for RestApplicationPath and use `bindConstant().annotatedWith(RestApplicationPath.class).to("/")` and post the result?

**Comment by BenDol** [comment]
Well its not doing it to all the calls so this will simply break all the other calls I believe.

**Comment by meriouma** [comment]
Ok, then maybe change this 
```
@Path("/")
public interface ManagementsProtocol extends Protocol {
```

**Comment by BenDol** [comment]
I don't think it will resolve it since it won't set it to anything when set to `"/"` needs to path to `"/managements"` I think the generator is duplicating the resources path.

**Comment by meriouma** [comment]
Yes it should, the generator will prepend the value bound to `RestApplicationPath` to all requests

**Comment by meriouma** [comment]
I should have said, Change this but keep your @Provides method

**Comment by BenDol** [comment]
Where does it get the `/managements` value from if I don't define it in the ManagementsProtocol?

**Comment by meriouma** [comment]
Hmm sorry I misread your code. I thought Rest.ROOT was equal to `"/" + MANAGEMENTS `

**Comment by BenDol** [comment]
Ah right no problem, I think the issue is in here: https://github.com/ArcBees/GWTP/blob/302d9ff27116097b91ffb50354b1ada0415f39fe/gwtp-core/gwtp-dispatch-rest/src/main/java/com/gwtplatform/dispatch/rest/client/core/DefaultUriFactory.java#L82

**Comment by meriouma** [comment]
Is ManagementsProtocol a sub resource?

**Comment by BenDol** [comment]
I would consider it sub resource yeah, just an example of how I can reproduce it myself.

**Comment by BenDol** [comment]
Perhaps here? https://github.com/ArcBees/GWTP/blob/302d9ff27116097b91ffb50354b1ada0415f39fe/gwtp-core/gwtp-dispatch-rest/src/main/java/com/gwtplatform/dispatch/rest/client/core/DefaultUriFactory.java#L91

**Comment by meriouma** [comment]
Ok, because if you have an `@Path(Managements.ROOT)` in the parent resource, then adding it on the sub-resource to might add the path twice

**Comment by BenDol** [comment]
Oh no, it's the base resource, sorry I see what you mean now. Never really used sub resources much.

**Comment by meriouma** [comment]
Hmm ok thanks. It's a bit hard to tell where the 2nd one is coming from without having a more complete view of your code

**Comment by BenDol** [comment]
Debugging the code the path is mapped correctly even up to this point:
```java
return new GwtHttpDispatchRequest(requestBuilder.send());
```
url: "http://127.0.0.1:8080/actions/api/managements/request_counts"

So not sure when the client is actually sending this out...

**Comment by BenDol** [comment]
Wow, okay sorry to waste your time guys! I've done some thorough digging and it turns out when a Spring controller returns an Object type without the @ResponseBody annotation it returns this error as a false positive for whatever reason... Really strange! Sorry again.

**Comment by meriouma** [comment]
No worries, glad you got it working!
