### ISSUE TITLE
GWTP as pure Java Framework

### ISSUE THREAD

**Issue by confile** [ArcBees/GWTP#708]
I have been using GWTP for quite a long time in a web environment with GWT. It works great. Recently, I read that google is working on Singular a pure Java MVC framework. 

@christiangoudreau Wouldn't it be great to have GWTP also as a pure Java framework. You just have to remove all the GWT specific part. The following things have to be done: 

- use GWT super-source when you have to emulate some of the Java functions that are not available in GWT
- replace GWT Generators with Java Annotation Processors
- Replace Gin DI framework with google Dagger2

That's it now you have a pure Java framework which is much more usable for a broader audience than GWTP is so far.

**Comment by christiangoudreau** [comment]
Hi Confile, 

We indeed have plans to Replace GWT generators with pure Java annotation. :D

As for replacing Gin with Dagger2, the problem we will probably face is to support both at the same time, but I don't see why we couldn't find a solution for that as well.

**Comment by confile** [comment]
I think there is no problem in replacing Gin with Dagger2 and Auto Factory. It works great together and I do not miss anything except for delayed bindings. But you can replace this with annotation processors.

**Comment by olafleur** [comment]
Thanks for your input @confile ! Closing as it's not an issue per se.
