### ISSUE TITLE
SuperDevMode with -noserver in eclipse

### ISSUE THREAD

**Issue by ddpardo** [ArcBees/GWTP#717]
Hi,

I am facing a strange problem with gwtp when developing against a local wildfly and or tomcat.

Here is the startup process
compile the application using maven clean install.
right click on the project -> run on server 
mvn gwt:debug

when looking to the deployment directory of the webapp i noticed the Project folder containing the **.nocache.js file and other gwt related classes are not deployed by eclipse. A project without gwtp does not have this issue...

![2015-07-31 13_52_08](https://cloud.githubusercontent.com/assets/2494889/9006847/1000dbf0-378c-11e5-8a45-5ae1d45e3c4d.png)

Im not sure if this is an eclipse or gwt or gwtp issue.. Did someone manage to use superdevmode and -noserver ?

**Comment by branflake2267** [comment]
I suggest adding a launcher directory that points out the war output path to solve many of the issues. With the noserver config, you'll need to use the bookmarklets to boot up sdm because the compiled folder will be in a tmp directory.

**Comment by ddpardo** [comment]
Hi branflake,

It seems to work when the launcherdir set in combination with alternating the web archive deployment. But im still confused why the folder is sometimes deployed and sometimes not by eclipse. I retested and it seems not gwtp related. my applogies.

Thanks

**Comment by branflake2267** [comment]
What type of resource is getting changed and not getting updated? I know of some cases in some apis where a file resources like html or maybe xml or some other resource that is processed by a generator, that generator may not be wired up for incremental compile so a full SDM restart is needed to run the generator.
