### ISSUE TITLE
NestedSlot ClassCastException

### ISSUE THREAD

**Issue by danielkaneider** [ArcBees/GWTP#729]
The _PresenterWidget.clearSlot_ method is very type safe, but this is not yet valid for _setInSlot_. Mainly, when you try doing
```
setInSlot(A_NESTED_SLOT, null)
```
this results in an exception. The main problem IMHO is, that NestedSlot should implement _IsRemovable_, otherwise the _return true_ in it's isRemovableMethod doesn't make much sense.

**Comment by rdwallis** [comment]
This problem couldn't be solved while maintaining backward compatibility.

It may work to cast the null:

`setInSlot(A_NESTED_SLOT, (NestedSlot) null)` but otherwise it's not calling the type safe method I think.

So use clearSlot for now and then we can fix this when we drop support for the old slots.

**Comment by danielkaneider** [comment]
The problem arises when firing a _RevealContentEvent_ with ```null```. I don't think the problem is the wrong mapping of the ```setInSlot``` method, but rather what is happening inside the new ```setInSlot``` method.

Adding ```RemovableSlot``` to ```NestedSlot``` should solve the problem, if that is the intended behaviour.

**Comment by rdwallis** [comment]
I don't have the gwtp code in front of me so this may be wrong and I can't do a PR

but at: https://github.com/ArcBees/GWTP/blob/master/gwtp-core/gwtp-mvp-client/src/main/java/com/gwtplatform/mvp/client/proxy/RevealContentHandler.java#L67

Replace line 67 & 68 with:

```
if (revealContentEvent.getContent() == null) {
   presenter.clearSlot((NestedSlot) revealContentEvent.getAssociatedType());
} else {
  presenter.setInSlot((NestedSlot) revealContentEvent.getAssociatedType(),
                                    revealContentEvent.getContent());
}
```

And it should solve the problem.
