### ISSUE TITLE
RestDispatch Exception Handler missing documentation

### ISSUE THREAD

**Issue by BenDol** [ArcBees/GWTP#733]
The link here returns page not found http://dev.arcbees.com/gwtp/communication/Exception-Handler.html

**Comment by olafleur** [comment]
Yes, you are right. The URL is in that page, right?
http://dev.arcbees.com/gwtp/communication/index.html

@Chris-V I can't seem to find the right content to point to on that URL. Do you know where it is?

**Comment by Chris-V** [comment]
Used to be that page
https://github.com/ArcBees/dev-site/blob/1a6bf73b2543b5572db2cac8857cdedcf8384055/site/src/main/markdown/gwtp/communication/Exception-Handler.md

So, documenting it is _eventually_ planned, but no point keeping it for
now...
