### ISSUE TITLE
"has no dependency" compiler warning

### ISSUE THREAD

**Issue by lukelast** [ArcBees/GWTP#738]
Using GWTP 1.5 with GWT 2.7 I get the following compiler warning.

[WARN] Type 'com.gwtplatform.mvp.shared.proxy.ParameterTokenFormatter' wants to reference type 'com.gwtplatform.common.shared.UrlUtils' but can't because module 'com.gwtplatform.mvp.MvpShared' has no dependency (neither direct nor transitive) on 'com.gwtplatform.common.ClientsCommon'.

**Comment by olafleur** [comment]
Thanks for reporting. We'll investigate on that whenever we have a little bit of time.

**Comment by lukelast** [comment]
Thanks, just let me know if you need any more information, or would like me to test something out.

**Comment by olafleur** [comment]
I've just tried a fresh new project on GWTP 1.5 with GWT 2.7 and I don't have this error.
Are you using something that is deprecated? Or did you create your project with an old version of GWTP and then updated it to the last version afterwards?

**Comment by lukelast** [comment]
I just noticed the warning goes away if I disable the `-incrementalCompileWarnings` compiler option.

**Comment by olafleur** [comment]
Super! Closing, then.

**Comment by lukelast** [comment]
Would be nice to get the warning fixed, because I want to keep `-incrementalCompileWarnings` turned on. I'll wait and see what happens with GWT 2.8 though.

**Comment by lukelast** [comment]
I tried GWT 2.8 beta1 and the warning is gone. In fact that compiler option is gone. So looks like this is a non issue.
Thanks!
