### ISSUE TITLE
where is @ProxyCodeSplitBundle processor located ?

### ISSUE THREAD

**Issue by sgkhode** [ArcBees/GWTP#742]
I want to see implementation of @ProxyCodeSplitBundle annotations's processor.

**Comment by olafleur** [comment]
I guess you are not looking for this, right?
https://github.com/ArcBees/GWTP/blob/master/gwtp-core/gwtp-mvp-client/src/main/java/com/gwtplatform/mvp/client/annotations/ProxyCodeSplitBundle.java

Could you please clarify your needs so that we can help you more?

**Comment by sgkhode** [comment]
Thanks. But I am more interested in code which is finding those classes which are annotated with @ProxyCodeSplitBundle. I want to see how it is extracting bundle class name and ID given as arguments in the annotations and what it does after that?

**Comment by olafleur** [comment]
Then, I suppose you are probably looking more for one of these, then : 
https://github.com/ArcBees/GWTP/blob/master/gwtp-core/gwtp-mvp-client/src/main/java/com/gwtplatform/mvp/rebind/PresenterInspector.java

https://github.com/ArcBees/GWTP/blob/master/gwtp-core/gwtp-mvp-client/src/main/java/com/gwtplatform/mvp/rebind/GinjectorGenerator.java

**Comment by sgkhode** [comment]
I understand that the @ProxyCodeSplitBundle makes providers injected to the our implementation of ProviderBundle  class. 
Is it possible to make use of ProviderBundle to bundle together relevant providers so that we have a split point of the relevant code?
