### ISSUE TITLE
GWTP 1.5.x Tabs don't get selected

### ISSUE THREAD

**Issue by avsgi09** [ArcBees/GWTP#744]
Upgrading a 1.4 app to 1.5.x we have found this problem with the GWTP Tabs infrastructure. This happens only if you use the new slots (NestedSlot, PermanentSlot, etc.).

If you select a tab the "active" styles aren't added - seems like the addStyleName & removeStyleName calls in the BaseTab class simply do nothing. The inactive style isn't removed and the active style isn't added: only the inactive style remain in the tab. 

This can be seen in the GWTP Tabs Sample with the browser inspector tools: if you click on any tab (be RoundTab, be SimpleTab) and inspect it's styles you'll see that all the tabs have the same style and background color. They only have the inactive CSS style (according to the tabs.gss file the selected tab should have #eaeaea as background color, but has #ccc)

**Comment by olafleur** [comment]
Thanks for noticing ! @jasonlemay or @LarryMatte could you take a look?

**Comment by filiphr** [comment]
Hi, we have the same problem with the new slots.

I have also pinpointed the problem. 

See [```TabContainer#setInSlot(Object, PresenterWidget)```](https://github.com/ArcBees/GWTP/blob/3f1bb47cf0c40fe7061bc15f981e14281aed22f3/gwtp-core/gwtp-mvp-client/src/main/java/com/gwtplatform/mvp/client/TabContainerPresenter.java#L211-L228). 

The ```TabContainer``` does not implement the new method [```PresenterWidget#setInSlot(IsSlot<T>, T)```](https://github.com/ArcBees/GWTP/blob/3f1bb47cf0c40fe7061bc15f981e14281aed22f3/gwtp-core/gwtp-mvp-client/src/main/java/com/gwtplatform/mvp/client/PresenterWidget.java#L475-L478).

And the main problem comes from the [```RevealContentHandler```](https://github.com/ArcBees/GWTP/blob/3f1bb47cf0c40fe7061bc15f981e14281aed22f3/gwtp-core/gwtp-mvp-client/src/main/java/com/gwtplatform/mvp/client/proxy/RevealContentHandler.java#L66-L72). When handling the method it is explicitly checked if slot is ```NestedSlot``` or not. If it is then the new method from the ```PresenterWidget``` is called. if it isn't then the old method is called.

I would say that a current workaround would be to not migrate to the new slots for the tabs. And then once there is a new release migrate that to the new slots.

Do you will fix this and release the next patch?

**Comment by olafleur** [comment]
@rdwallis Could you take a look? Thanks!

**Comment by olafleur** [comment]
@rdwallis ping

**Comment by timeu** [comment]
@olafleur: I created a pull request. 
BTW: The `TabContainerPresenter` still used the untyped [SLOT mechanism](https://github.com/ArcBees/GWTP/blob/master/gwtp-core/gwtp-mvp-client/src/main/java/com/gwtplatform/mvp/client/TabContainerPresenter.java#L52). This should probably also be migrated to `IsSlot`. But I guess this can be done in a separate pull request

**Comment by olafleur** [comment]
Thanks a lot ! We will review it.
