### ISSUE TITLE
Using ProviderBundle from gwtplatform to bundle together non-presenter classes

### ISSUE THREAD

**Issue by sgkhode** [ArcBees/GWTP#747]
For presenters, we can use @ProxyCodeSplitBundle to bundle the presenters in a ProviderBundle implementation.

How can we bundle the non-presenter classes together in a ProviderBundle?

**Comment by olafleur** [comment]
@Elrhino gave you an answer here, I think : http://stackoverflow.com/questions/33806771/using-providerbundle-from-gwtplatform-to-bundle-together-non-presenter-classes

**Comment by olafleur** [comment]
Could you give more details about what is your use case?

**Comment by sgkhode** [comment]
we have several non-presenter classes which are coming under initial download fragment of the compiler report. We want to bundle them together and put them behind a split point and reduce the initial download size. 
I am looking for a generic way to use ProviderBundle.
I tried creating Provider as below:
```
class XYZProvider implements Provider<XYZ>
{
         @Override
    public XYZ get()
    {
        return new XYZ();
    }
}
```
And then this provider is contributed using GIN multibinder as Set. we are using Set because we want to contribute several classes and need a maintainable way of doing it.
The Set is injected in the ProviderBundle class implementation.
```
    @Inject
    public XYZClassesProviderBundle( @Named( NameTokens.PROVIDER_BUNDLE ) Set<Provider> bundle )
    {
        super( bundle.size() );
        int i = 0;
        for( Provider loc : bundle )
        {
            providers[i] = loc;
            i++;
        }
    }
``` 

But with above code, I am getting my classes in initial download fragment. please suggest if there is better way of doing it.

**Comment by olafleur** [comment]
Maybe that blog post can help you understand a little better how it's working. Feel free to reopen if it does not answer your question : http://blog.arcbees.com/2015/12/08/code-splitting-for-non-presenters-in-gwtp/
