### ISSUE TITLE
Help the coder understand gwtp errors

### ISSUE THREAD

**Issue by rsallar** [ArcBees/GWTP#751]
When developing with GWTP I do normally start with a working code that suddenly ends with an error with just a minor change in gwt.xml module descriptor or main clientmodule.

This is something that could be related more on GWT than GWTP.
Actually I'm stucked with this error:

    "There must have been an issue generating the ApplicationController. Please check your module configuration, ensure there are no compile errors in your source code and ensure you are not importing sources that cannot be compiled by GWT."

Googling this error is useless.  It leds to http://javadox.com/com.gwtplatform/gwtp-mvp-client/1.5.1/constant-values.html

Now I'm going to revert all my changes until I find the problem. I guess this kind of problems are related to the heavy use of GIN (which per se does not make compile time validation). Maybe chaging to dagger2 should help.

You could find the code here
https://github.com/rsallar/contesencatala/tree/gwtperror
Thanks.

**Comment by rsallar** [comment]
I found the problem.
Remove this line from gwt.xml module descriptor and the app works again.

<set-property name="gwt.logging.enabled" value="TRUE"/>     

I don't know why. It seems a valid gwt logging property to me.

**Comment by BenDol** [comment]
If you check the super dev mode console you will find the actual error, this error message is just stating that there is a problem and it couldn't generate the ApplicationController.

**Comment by rsallar** [comment]
ok. thanks.
