### ISSUE TITLE
GWT2.8-beta1: java.lang.RuntimeException: Encountered repeated errors resulting in an infinite loop.

### ISSUE THREAD

**Issue by confile** [ArcBees/GWTP#753]
When running on GWT 2.7 with GWTP 1.5.1 I have no problems but with GWT 2.8-beta1 I get the following error when doing: 

```
    PlaceRequest request = new PlaceRequest.Builder()
        .nameToken(NameTokens.start)
        .build();
    placeManager.revealPlace(request);
```

error: 

```
Uncaught java.lang.RuntimeException: Encountered repeated errors resulting in an infinite loop. Make sure all users have access to the pages revealed by revealErrorPlace and revealUnauthorizedPlace. (Note that the default implementations call revealDefaultPlace)
```

In my ClientModule I have: 

```
    bindConstant().annotatedWith(DefaultPlace.class).to(NameTokens.start);
    bindConstant().annotatedWith(ErrorPlace.class).to(NameTokens.start);
    bindConstant().annotatedWith(UnauthorizedPlace.class).to(NameTokens.start);
```

This works with no problems in GWT 2.7 but GWT 2.8-beta1 fails.

**Comment by confile** [comment]
Is there any workaround here other than using GWT 2.7?

**Comment by olafleur** [comment]
Hi @confile . We have a few projects running with GWTP 1.5.1 and GWT 2.8-beta1

For example, I recently started a pull request to convert our BeeStore example to GWT 2.8-beta1 and everything seems to run nicely (see https://github.com/ArcBees/BeeStore/pull/127/files)

Without that PlaceRequest change it works fine?

**Comment by confile** [comment]
Works fine with GWT 2.8-SNAPSHOT.
