### ISSUE TITLE
GWTP same project for differents webs for different clients

### ISSUE THREAD

**Issue by riparrag** [ArcBees/GWTP#757]
I have a big large project, and must compile differents webs for our different clients ( before GWTP these were different entry points with different compilations)

Now i need gwtp to to the similar thing, i tried to write two gwt.xml for each one but they try to inject all.

My example:

big-project:
src/ common /
       core /
       app1-especifics /
       app2-especifics /
   app1.gwt.xml
   app2.gwt.xml
war /
   app1-index.html
   app2-index.html

need to compile and deploy them separately.

Thanks!

**Comment by olafleur** [comment]
I would suggest asking your questions on the forum : https://groups.google.com/forum/#!forum/gwt-platform

We try to keep issues for bugs in GWTP. Thanks !
