### ISSUE TITLE
Site: "Create an App from Scratch": bad link to "Beginner's Tutorial"

### ISSUE THREAD

**Issue by murraycu** [ArcBees/GWTP#762]
This page
http://dev.arcbees.com/gwtp/get-started/from-scratch/index.html
has a link:
"Note: For a more in-depth guide on creating a new GWTP application, you can read the Beginner's Tutorial", where the url on "Beginners Tutorial" takes you to the very same page that you are on, via this URL:
http://dev.arcbees.com/%7B%7B#gwtp.doc.url.beginner_tutorial}}

**Comment by olafleur** [comment]
I've fixed the URL. It should be deployed soon. Thanks for your contribution !

**Comment by murraycu** [comment]
Thanks. Note to self: This was the commit: https://github.com/ArcBees/dev-site/commit/f720d7f5025c7c051f4debe6a9006b2e17208724

**Comment by olafleur** [comment]
It has been deployed.
