### ISSUE TITLE
Breaking API changes when upgrading from 1.5.1 to 1.5.2+

### ISSUE THREAD

**Issue by danielkaneider** [ArcBees/GWTP#788]
It appears that the 1.5.2 (and also the 1.5.3) release were not created based on the 1.5.1 branch. Specifically the commit e92340fdae547494d364278e662f0f4c7e143dc5 is present in 1.5.1, but not in 1.5.2. Since this introduces breaking API changes, an upgrade is not easily possible. To be more specific, ```PlaceRequest``` is missing some methods.

Please also add some release notes when publishing a new version. There isn't any changelog, except the commits in github..

**Comment by olafleur** [comment]
@meriouma could you take a look?

**Comment by meriouma** [comment]
Sorry about that, but it's the other way around. 1.5.1 is the erroneous version. We remove deprecated code after 2 minor versions. In this case, the commit e92340f should not have been in 1.5.1, as it's not in 1.5. It removes code deprecated in version 1.3.
