### ISSUE TITLE
Consider improving adding to OrderedSlot

### ISSUE THREAD

**Issue by bmorris591** [ArcBees/GWTP#797]
Currently `addToSlot` with a `OrderedSlot` does the following:

```java
List<Comparable<Comparable<?>>> list = orderedSlots.get(slot);
list.add((Comparable<Comparable<?>>) content);
Collections.sort(list);
int index = Collections.binarySearch(list, (Comparable<Comparable<?>>) content);

InsertPanel insertPanel = (InsertPanel) hasWidgetSlots.get(slot);
insertPanel.insert(content.asWidget(), index);
```

So the steps are:

 1. add the new item to the `List`
 2. `sort` the `List`
 3. find the `index` of the new item
 4. add the new item to the `InsertPanel` at the correct index

This can be improved to remove the sorting step.

 1. use `binarySearch` to find the index the item _would be_ added at  
 2. `add` the item at this index
 3. add the new item to the `InsertPanel` at the correct index

This works because we have an invariant that the items in the `List` must always be already sorted.

**Comment by olafleur** [comment]
Thanks a lot for your comment!
Would you want to submit a pull request with these changes?
We could help you along the way, if you need it.

**Comment by bmorris591** [comment]
@olafleur sure thing - watch this space.

**Comment by olafleur** [comment]
Great. ;)
