### ISSUE TITLE
Improve DispatchService error logging

### ISSUE THREAD

**Issue by filiphr** [ArcBees/GWTP#803]
Currently the `AbstractDispatchServiceImpl` uses the logger attached to itself to log the exceptions which are thrown during the `Dispatch#execute(Action)` method.

Is there a possibility to modify this dispatch service so the error handling is passed to something else? This would allow us to do custom logging based on the type of the exception. For example sometimes we have business exceptions which are handled on the client side and there is no point in logging their entire stacktraces to the log file.

I would like to hear your opinion about an extension (improvement) of the `AbstractDispatchServiceImpl` in this direction.

**Comment by shawnjohnson** [comment]
We are having the same issue, seeing a lot of large stacks in our logs for ActionExceptions that we more or less know that we've thrown to the client to handle.  We'd like to log the message so we know that there are X occurrences of a particular exception, but in most cases we don't need the logging of the stack.

**Comment by filiphr** [comment]
I tried to do something that I think would make it much easier to add custom logic to the log handler.

I created the pull request #808. 

@shawnjohnson will something like this help you achieve what you want?
