### ISSUE TITLE
JAX-RS interfaces without RestAction wrappers

### ISSUE THREAD

**Issue by Tillerino** [ArcBees/GWTP#809]
Is there a way to use JAX-RS interfaces directly in GWTP? I mean

```
@GET
@Path("/wherever")
SomeObject doSomething();
```

vs.

```
@GET
@Path("/wherever")
RestAction<SomeObject> doSomething();
```

The obvious advantage being of course that the interface can be used in the backend as well. I could swear I read how to do this somewhere, but I can't find it anymore.

**Comment by meriouma** [comment]
Yes, it is provided as an extension to GWTP's REST-Dispatch : [dispatch-rest-delegates](https://github.com/ArcBees/gwtp-extensions).

You can look into the [carstore sample](https://github.com/ArcBees/GWTP-Samples/tree/master/carstore/src/main/java/com/gwtplatform/carstore/shared/api) or the [documentation](http://dev.arcbees.com/gwtp/communication/resource-delegates.html)
