### ISSUE TITLE
Compile failure path for type 'com.gwtplatform.mvp.client.GeneratedMvpEntryPoint'

### ISSUE THREAD

**Issue by olgagrinberg** [ArcBees/GWTP#812]
In my project I upgraded to gwt 2.8 and  gwtp-mvp-client 2.0-SNAPSHOT from gwt 2.7 and gwtp-mvp-client 1.5.3.
Now I am getting a build error: 
"   Finding entry point classes
     Tracing compile failure path for type 'com.gwtplatform.mvp.client.GeneratedMvpEntryPoint'
     [ERROR] Hint: Check that the type name 'com.gwtplatform.mvp.client.GeneratedMvpEntryPoint' is really what you meant
    [ERROR] Hint: Check that your classpath includes all required source roots"

**Comment by meriouma** [comment]
GWTP 2.0 isn't documented and requires APT to be setup correctly to generate the classes. We removed GWT generators usages. You can look at https://github.com/ArcBees/GWTP-Samples for examples on how to setup your pom files. The samples are updated to work with the latest snapshot.

**Comment by sst2k2** [comment]
I am facing the same ERROR. I used the GWTP-Sample-basic pom and migrated my code to the sample project. The permutations gets compiled successfully but GeneratedMvpEntryPoint class is not generated hence overall compilation fails. Please suggest how this class can be generated. What could be missing??
