### ISSUE TITLE
Calling RestDispatchAsyncModule.Builder.core().responseDeserializer() has no effect on the binding

### ISSUE THREAD

**Issue by emweber** [ArcBees/GWTP#826]
I want to replace the ResponseDeserializer but that does not work:
`new RestDispatchAsyncModule.Builder().core().responseDeserializer(xxx)`

From the call hierarchy at configure() time, one can see that
`configureDispatch()`
calls `builder.getCoreModule()`
calls `core()`, which creates a **new CoreModuleBuilder** object so all settings made through the call of `responseDeserializer` or other methods is lost.

**Comment by Chris-V** [comment]
Closing as this seems resolved.
